language: python
python:
    - "2.7"
    - "3.3"
before_install:
    # Installing Arpeggio as a dependency
    - git clone --depth=50 --branch=master git://github.com/igordejanovic/Arpeggio.git
    - cd Arpeggio && python setup.py install
install:
    - python setup.py install
script:
    - py.test tests/functional
