site_name: textX

site_description: A meta-language for building Domain-Specific Languages (DSLs)
site_author: Igor Dejanović

repo_url: https://github.com/igordejanovic/textX
google_analytics: ['UA-68681917-1', 'igordejanovic.net']
theme: readthedocs

pages:
- Home: index.md
- User Guide:
    - Grammar: grammar.md
    - Meta-model: metamodel.md
    - Model: model.md
    - Visualization: visualization.md
    - Error handling: error_handling.md
    - Debugging: debugging.md
    - textx command: textx_command.md
- Tutorials:
    - Hello World: tutorials/hello_world.md
    - Robot: tutorials/robot.md
    - Entity: tutorials/entity.md
    - State Machine: tutorials/state_machine.md
- About:
    - Comparison: about/comparison.md
    - Discuss: about/discuss.md
    - Contributing: about/contributing.md
    - License: about/license.md

markdown_extensions:
    - admonition:
    - toc:
        permalink: True

copyright: Copyright &copy; 2016 <a href="http://igordejanovic.net/">Igor Dejanović</a>.

